#!/bin/sh

# TODO: Check the cert validity and ignore if there's at least 30 days left
# Obviously if the cert isn't present, there's no validity on it
openssl genrsa -out db.rosuav.com.key -traditional 4096
openssl req -new -key db.rosuav.com.key -out db.rosuav.com.csr -subj '/CN=db.rosuav.com'
echo 'subjectAltName=DNS:ipv4.rosuav.com,DNS:sikorsky.rosuav.com' | openssl x509 -req -passin pass: -in db.rosuav.com.csr -CA sugarmill.rosuav.com.pem -CAkey sugarmill.rosuav.com.key -out db.rosuav.com.pem -days 90 -sha256 -extfile -
rm db.rosuav.com.csr # Delete the bag of sugar
cp db.rosuav.com.* /home/rosuav/stillebot/
chown rosuav: /home/rosuav/stillebot/db.rosuav.com.*
cp db.rosuav.com.* /etc/postgresql/16/main/
chown postgres: /etc/postgresql/16/main/db.rosuav.com.*
systemctl reload postgresql
cat db.rosuav.com.* | ssh gideon sugar-mill/update_db_key.sh
